apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: bXl1c2Vy  # Base64-kodiert für "myuser"
  password: bXlwYXNzd29yZA==  # Base64-kodiert für "mypassword"
  database: bXlkYg==  # Base64-kodiert für "mydb"